version: 2
updates:

# Maintain dependencies for GitHub Actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  assignees:
  - jhillairet

# Maintain dependencies for python
- package-ecosystem: pip
  directory: /
  schedule:
    interval: monthly
  assignees:
  - jhillairet
