language: python
python:
  - 2.7


before_install:
  - sudo apt-get install python-scipy python-matplotlib
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script: nosetests --exclude-dir=vi
