language: python
python:
  - 2.7

before_install:
  # Install conda
  - sudo pip install conda
  # install deps
  - sudo conda init
  - sudo conda update --yes  conda 
  - deps='pip numpy pandas requests nose numpydoc sphinx'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  
# command to install dependencies
install: 
  - pip install -r tools/travis-requirements.txt
  - python setup.py install
# command to run tests
script: 
  - nosetests --exclude-dir=vi
