[tool.poetry]
name = "scikit-rf"
version = "0.23.1"
description = "Object Oriented Microwave Engineering"
authors = ["Alex Arsenovic <alexanderarsenovic@gmail.com>"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://scikit-rf.org/"
repository = "https://github.com/scikit-rf/scikit-rf"
documentation = "https://scikit-rf.readthedocs.io/en/latest/"
keywords = [
    "engineering", 
    "electronics", 
    "microwave-engineering", 
    "radio-frequency", 
    "touchstone"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Communications :: Ham Radio",
    "Topic :: Scientific/Engineering"]
packages = [{include="skrf"}]

[tool.poetry.dependencies]
python = "^3.7.1"
numpy = "^1.21"
scipy = "^1.6.1"
pandas = "^1.3.4"

# Optional Runtime Dependencies
matplotlib = {version = "^3.5.3", optional=true}
openpyxl = {version = "^3.0.10", optional=true}
networkx = {version = "^2.6.3", optional=true}
PyVISA = {version="^1.12.0", optional=true}

# Test & Doc Dependencies
pytest = {version="^7", optional=true}
coverage = {version="^6", optional=true}
flake8 = {version="^5.0.4", optional=true}
pytest-cov = {version="^3.0.0", optional=true}
nbval = {version="^0.9.6", optional=true}
ipython = {version="^7", optional=true}
ipykernel = {version="^6.15.2", optional=true}
ipywidgets = {version="^8.0.2", optional=true}
python-ivi = {version="^0.14.9", optional=true}
jupyter-client = {version="^7.3.5", optional=true}
sphinx-rtd-theme = {version="^1.0.0", optional=true}
Sphinx = {version="^4", optional=true}
nbsphinx = {version="^0.8.9", optional=true}


[tool.poetry.extras]
plot = ["matplotlib"]
xlsx = ["openpyxl"]
netw = ["networkx"]
visa = ["pyvisa"]
test = ["pytest", "coverage", "flake8", "pytest-cov", "nbval"]
docs = ["ipython", "ipykernel", "ipywidgets", "python-ivi", 
        "jupyter-client", "sphinx-rtd-theme", "sphinx", "nbsphinx"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
