channels:
    - conda-forge
dependencies:
    - python
    - pandas
    - setuptools
    - ipython
    - numpy
    - scipy
    - matplotlib
    - mock
    - nose
    - future
    - pandoc
    - nbconvert=4.2
    - ipykernel
    - pip:
        - git+https://github.com/arsenovic/nbsphinx.git@master
