name: Test-Notebooks

# Run every time a new commit is pushed
on: push

jobs:
  # Set the job key
  test-notebooks:
    # Name the job
    name: Test Jupyter Notebooks
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # checkout the code 
      - name: Checkout code
        uses: actions/checkout@v2
      # install python env
      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: jupyter-actions
          python-version: 3.7
      # install python packages...
      - name: Install other dependances
        shell: bash -l {0}        
        run: |
          conda activate jupyter-actions
          conda install numpy matplotlib scipy pandas networkx nose pip ipython pytest qtpy numpydoc sphinx pyqtgraph
          pip install -r tools/travis-requirements.txt
          #conda install -c conda-forge scikit-rf
          pytest skrf

